/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica1;

/**
 *
 * @author Paola
 */
public class FrameInicio extends javax.swing.JPanel {

    /**
     * Creates new form FrameInicio
     */
    public FrameInicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        leer = new javax.swing.JButton();
        jugar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 51, 51));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("04b", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 102, 0));
        jLabel1.setText("SCRABBLE");
        add(jLabel1);
        jLabel1.setBounds(110, 70, 200, 60);

        leer.setBackground(new java.awt.Color(255, 255, 0));
        leer.setFont(new java.awt.Font("8BIT WONDER", 0, 11)); // NOI18N
        leer.setText("LEER ARCHIVO");
        leer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leerActionPerformed(evt);
            }
        });
        add(leer);
        leer.setBounds(110, 140, 180, 40);

        jugar.setFont(new java.awt.Font("8BIT WONDER", 0, 11)); // NOI18N
        jugar.setText("Jugar");
        jugar.setEnabled(false);
        add(jugar);
        jugar.setBounds(110, 200, 180, 40);

        jLabel2.setFont(new java.awt.Font("04b", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SCRABBLE");
        add(jLabel2);
        jLabel2.setBounds(110, 70, 200, 60);
    }// </editor-fold>//GEN-END:initComponents

    private void leerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leerActionPerformed
        // TODO add your handling code here:
        MetodosPrincipal me = new MetodosPrincipal();
        jugar.setText(me.AbrirArchivo()); 
            
    }//GEN-LAST:event_leerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jugar;
    private javax.swing.JButton leer;
    // End of variables declaration//GEN-END:variables
}
